# Clippy configuration for TVA
# https://doc.rust-lang.org/clippy/

# Disallowed: any kind of type erasure
disallowed-macros = ["unreachable"]

# Maximum type complexity for public interfaces
type-complexity-threshold = 250

# Allow certain lints
allow = [
  "module_name_repetitions",  # tva-core::core is fine
]

# Deny these (unsafe_code enforced by #![forbid] in lib.rs)
