APPLY_FIXES: none
DEFAULT_BRANCH: main

ENABLE_LINTERS:
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_PRETTIER
  - SPELL_CODESPELL
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT
  - REPOSITORY_GITLEAKS

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdownlint.json"
YAML_YAMLLINT_CONFIG_FILE: ".yamllint.yaml"
SPELL_CODESPELL_CONFIG_FILE: ".codespellrc"

EXCLUDED_DIRECTORIES:
  - ".git"
  - "target"
  - "node_modules"
  - "pkg"
  - ".agents"
  - ".opencode"

PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
REPORT_OUTPUT_FOLDER: none
VALIDATE_ALL_CODEBASE: false
