[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "MIT OR Apache-2.0",
    "0BSD",
    "0BSD OR MIT OR Apache-2.0",
    "BSL-1.0",
    "ISC",
    "Zlib",
    "MPL-2.0",
    "Unicode-3.0",
    "CC0-1.0",
]
