[package]
name = "tva-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI for Temporal Video Analyzer"

[features]
default = ["smooth-savgol"]
smooth-savgol = ["tva-core/smooth-savgol"]
decode-ffmpeg-native = ["tva-core/decode-ffmpeg-native"]

[dependencies]
tva-core = { path = "../tva-core", features = [
    "compare-image",
    "decode-images",
] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
csv = "1"
