[package]
name = "tva-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI for Temporal Video Analyzer"

[dependencies]
tva-core = { path = "../tva-core", features = [
    "compare-image",
    "smooth-savgol",
    "decode-images",
] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
csv = "1"
