[package]
name = "tva-ffi"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["TVA Contributors"]
description = "C FFI shared library for tva-core"
homepage = "https://github.com/tayuLuc/tva"
repository = "https://github.com/tayuLuc/tva"
keywords = ["video", "analysis", "ffi"]
categories = ["external-ffi-bindings", "multimedia::video"]

[dependencies]
tva-core = { path = "../tva-core" }

[lib]
crate-type = ["cdylib", "staticlib"]
